### ISSUE TITLE
'module' object has no attribute 'Mifare'

### ISSUE THREAD

**Issue by paparts** [svvitale/nxppy#20]
I got an error using the readme second example

:~$ _python read.py_

```
Traceback (most recent call last):
  File "read.py", line 1, in <module>
    import nxppy
  File "/home/pi/NFC/nxppy.py", line 4, in <module>
AttributeError: 'module' object has no attribute 'Mifare'
```

using help also throws the same error

```
>>> help('nxppy')
problem in nxppy - <type 'exceptions.AttributeError'>: 'module' object has no attribute 'Mifare'
```

**Comment by paparts** [comment]
Managed to fix the problem with pip.

Inside the folder together with the _read.py_ file
``pip install nxppy``
