### ISSUE TITLE
No module named nxppy no exist 

### ISSUE THREAD

**Issue by forsanta** [svvitale/nxppy#25]
hello,
try to install on a pi2 in debian 7.8
version 1.3.2 
i've this error 
NOTE: To compile programs with wiringPi, you need to add:
    -lwiringPi
  to your compile line(s) To use the Gertboard, MaxDetect, etc.
  code (the devLib), you need to also add:
    -lwiringPiDev
  to your compile line(s).

[Running ldconfig]
[Downloading NXP Reader Library]
--2015-12-13 23:32:14--  http://www.nxp.com/redirect/explore-nfc-dev_latest
Résolution de www.nxp.com (www.nxp.com)... 23.214.131.133
Connexion vers www.nxp.com (www.nxp.com)|23.214.131.133|:80...connecté.
requête HTTP transmise, en attente de la réponse...302 Moved Temporarily
Emplacement: http://www.nxp.com/documents/software/SW282814.zip [suivant]
--2015-12-13 23:32:16--  http://www.nxp.com/documents/software/SW282814.zip
Réutilisation de la connexion existante vers www.nxp.com:80.
requête HTTP transmise, en attente de la réponse...302 Moved Temporarily
Emplacement: http://www.nxp.com/documents/application_note/SW282814.zip [suivant]
--2015-12-13 23:32:16--  http://www.nxp.com/documents/application_note/SW282814.zip
Réutilisation de la connexion existante vers www.nxp.com:80.
requête HTTP transmise, en attente de la réponse...404 Not Found
2015-12-13 23:32:17 ERREUR 404: Not Found.

Archive:  nxp.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of nxp.zip or
        nxp.zip.zip, and cannot find nxp.zip.ZIP, period.
tar (child): neard-explorenfc_*.orig.tar.gz : open impossible: Aucun fichier ou dossier de ce type
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
./get_nxpRdLib.sh: ligne 50 : cd: neard-explorenfc-*: Aucun fichier ou dossier de ce type
[Running bootstrap]
./get_nxpRdLib.sh: ligne56: ./bootstrap: Aucun fichier ou dossier de ce type
[Configuring NXP Reader Library]
./get_nxpRdLib.sh: ligne59: ./configure: Aucun fichier ou dossier de ce type
[Building NXP Reader Library]
./get_nxpRdLib.sh: ligne 62 : cd: nxprdlib: Aucun fichier ou dossier de ce type
make: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.
Traceback (most recent call last):
  File "setup.py", line 53, in <module>
    cmdclass = {'build': build_nxppy})
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 30, in run
    self.execute(compile, [], 'compiling NxpRdLib')
  File "/usr/lib/python2.7/distutils/cmd.py", line 349, in execute
    util.execute(func, args, msg, dry_run=self.dry_run)
  File "/usr/lib/python2.7/distutils/util.py", line 404, in execute
    func(*args)
  File "setup.py", line 21, in compile
    nxprdlib_dir = glob('neard-explorenfc-*/nxprdlib')[0]
IndexError: list index out of range

after i try to test the nfc card reader and i've this bug
Traceback (most recent call last):
  File "read_nfc.py", line 1, in <module>
    import nxppy
ImportError: No module named nxppy

do you have some idea for this bug ?

**Comment by forsanta** [comment]
the same as https://github.com/svvitale/nxppy/issues/24
